[build]
builder = "nixpacks"
buildCommand = "npm install && cd server && npm install && cd ../client && npm install && cd .. && npx prisma generate && cd server && npm run build && cd ../client && npm run build"

[deploy]
startCommand = "sh scripts/start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
